[package]
name = "raycaster"
version = "0.1.0"
authors = ["adamgemmell <gemmell.adam+github@gmail.com>"]
build = "build.rs"

[dependencies]
num = "0.1"

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["bundled"]